<?php

namespace AdminBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindAll()
{
return $this->createQueryBuilder('a')->getQuery()->getResult();
}

public function myFindOne($id)
{
// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
$qb = $this->createQueryBuilder('a')
->where('a.id = :id')
->setParameter('id', $id);
return $qb->getQuery()->getResult()[0];
}


}
