admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:index }

admin_formpage:
    path:     /admin/form
    defaults: { _controller: AdminBundle:Default:form }

admin_tablepage:
    path:     /admin/table
    defaults: { _controller: AdminBundle:Default:table }
