services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#    admin.language.interactive_login_listener:
#        class: AdminBundle\EventListener\LanguageListener
#        calls:
#            - [ setSession, [@session] ]
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: setLocaleForAuthenticatedUser }

    admin.language.kernel_request_listener:
        class: AdminBundle\EventListener\LanguageListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocaleForUnauthenticatedUser }
