mobile_app:
    resource: "@MobileAppBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
            _locale: en|fr

business_model:
    resource: "@BusinessModelBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_change:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

fos_user_edit:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_security_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /{_locale}/
    requirements:
            _locale: en|fr

fos_user_security_logout:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /{_locale}/
    requirements:
            _locale: en|fr

fos_user_registration_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /{_locale}/register/
    requirements:
            _locale: en|fr
