mobile_app:
    resource: "@MobileAppBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

business_model:
    resource: "@BusinessModelBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_change:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

fos_user_edit:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
