business_model_homepage:
    path:     /hello/{name}
    defaults: { _controller: BusinessModelBundle:Default:index }

business_model_login:
    path:     /verifierLogin
    defaults: { _controller: BusinessModelBundle:User:login }

business_model_register:
    path:     /verifierInscription
    defaults: { _controller: BusinessModelBundle:User:register }

business_model_supprimerActivite:
    path:     /supprimerActivite/{id}
    defaults: { _controller: BusinessModelBundle:Activite:supprimer }
    requirements:
              id: \d+

business_model_listeDestinations:
    path:     /listeDestinations
    defaults: { _controller: BusinessModelBundle:Activite:listeDestinations }

business_model_endPaymentpage:
    path:     /payment/end
    defaults: { _controller: BusinessModelBundle:Default:finalisePaiement }

business_model_endPaymentStripepage:
    path:     /payment/end/stripe
    defaults: { _controller: BusinessModelBundle:Default:finalisePaiementStripe }

business_model_validatePaymentpage:
    path:     /payment/validate
    defaults: { _controller: BusinessModelBundle:Default:validerPaiement }

business_model_reportActivitypage:
    path:     /report/activity/{user}/{activity}/{phone}/{email}
    defaults: { _controller: BusinessModelBundle:Default:reportActivite }

business_model_reportpage:
    path:     /report/{user}/{message}/{phone}/{email}
    defaults: { _controller: BusinessModelBundle:Default:report }

business_model_resetpage:
    path:     /reset/{user}/{password}
    defaults: { _controller: BusinessModelBundle:Default:reset }

business_model_invoicepage:
    path:     /invoice/{user}
    defaults: { _controller: BusinessModelBundle:Default:invoice }

business_model_statementpage:
    path:     /statement/{guide}/{tourist}/{phone}/{email}
    defaults: { _controller: BusinessModelBundle:Default:statement }
