mobile_app_activity_editpage:
    path:     /mobapp/activity/edit
    defaults: { _controller: MobileAppBundle:Activity:edit }

mobile_app_activity_searchpage:
    path:     /mobapp/activity/search
    defaults: { _controller: MobileAppBundle:Activity:search }

mobile_app_activity_categoriespage:
    path:     /mobapp/activity/categories
    defaults: { _controller: MobileAppBundle:Activity:categories }

mobile_app_activity_searchresultpage:
    path:     /mobapp/activity/searchresult/{page}
    defaults: { _controller: MobileAppBundle:Activity:searchresult }

mobile_app_activity_searchresultallpage:
    path:     /mobapp/activity/searchresult/all
    defaults: { _controller: MobileAppBundle:Activity:searchresultall }

mobile_app_activity_testpage:
    path:     /mobapp/test
    defaults: { _controller: MobileAppBundle:Activity:test }

mobile_app_activity_listpage:
    path:     /mobapp/activity/list/{page}
    defaults: { _controller: MobileAppBundle:Activity:list }

mobile_app_activity_newspage:
    path:     /mobapp/activity/new
    defaults: { _controller: MobileAppBundle:Activity:new }

mobile_app_activity_toplistpage:
    path:     /mobapp/activity/toplist/{page}
    defaults: { _controller: MobileAppBundle:Activity:toplist }

mobile_app_activity_toppage:
    path:     /mobapp/activity/top
    defaults: { _controller: MobileAppBundle:Activity:top }

mobile_app_activity_page:
    path:     /mobapp/activity/show/{id}
    defaults: { _controller: MobileAppBundle:Activity:show }

mobile_app_activity_userpage:
    path:     /mobapp/activity/user/{iduser}/{numpage}
    defaults: { _controller: MobileAppBundle:Activity:user }

mobile_app_activity_deletepage:
    path:     /mobapp/activity/delete
    defaults: { _controller: MobileAppBundle:Activity:delete }

mobile_app_activity_uploadpage:
    path:     /mobapp/activity/image/upload
    defaults: { _controller: MobileAppBundle:Activity:upload }

mobile_app_user_loginpage:
    path:     /mobapp/user/login
    defaults: { _controller: MobileAppBundle:User:login }

mobile_app_user_registerpage:
    path:     /mobapp/user/register
    defaults: { _controller: MobileAppBundle:User:register }

mobile_app_user_updatepage:
    path:     /mobapp/user/update
    defaults: { _controller: MobileAppBundle:User:update }

mobile_app_user_languespage:
    path:     /mobapp/user/langues
    defaults: { _controller: MobileAppBundle:User:langues }

mobile_app_user_homepage:
    path:     /mobapp/user/home
    defaults: { _controller: MobileAppBundle:User:home }

mobile_app_user_reportActivitypage:
    path:     /mobapp/user/report/activity
    defaults: { _controller: MobileAppBundle:User:reportSurActivite }

mobile_app_user_reportpage:
    path:     /mobapp/user/report
    defaults: { _controller: MobileAppBundle:User:report }

mobile_app_user_resetpage:
    path:     /mobapp/user/reset
    defaults: { _controller: MobileAppBundle:User:resetPassword }

mobile_app_reservation_editpage:
    path:     /mobapp/reservation/editPanier
    defaults: { _controller: MobileAppBundle:Reservation:editPanier }

mobile_app_reservation_deletepage:
    path:     /mobapp/reservation/deletePanier
    defaults: { _controller: MobileAppBundle:Reservation:deletePanier }

mobile_app_reservation_page:
    path:     /mobapp/reservation/show
    defaults: { _controller: MobileAppBundle:Reservation:show }

mobile_app_reservation_nombrepage:
    path:     /mobapp/reservation/number
    defaults: { _controller: MobileAppBundle:Reservation:nombre }

mobile_app_reservation_historypage:
    path:     /mobapp/reservation/activities/history
    defaults: { _controller: MobileAppBundle:Reservation:activitiesHistory }

mobile_app_creerpayment_paypal_page:
    path:     /mobapp/payment/creer/paypal
    defaults: { _controller: MobileAppBundle:Payment:creerPaiementPaypal }

mobile_app_executepayment_paypal_page:
    path:     /mobapp/payment/execute/paypal
    defaults: { _controller: MobileAppBundle:Payment:executerPaiementPaypal }

mobile_app_page:
    path:     /mobapp/page/{page}
    defaults: { _controller: MobileAppBundle:Page:prendrepage }
