mobile_app_activity_addpage:
    path:     /mobapp/activity/add
    defaults: { _controller: MobileAppBundle:Activity:add }

mobile_app_activity_uploadpage:
    path:     /mobapp/activity/upload
    defaults: { _controller: MobileAppBundle:Activity:upload }
