mobile_app_activity_editpage:
    path:     /mobapp/activity/edit
    defaults: { _controller: MobileAppBundle:Activity:edit }

mobile_app_activity_searchpage:
    path:     /mobapp/activity/search
    defaults: { _controller: MobileAppBundle:Activity:search }

mobile_app_activity_searchresultpage:
    path:     /mobapp/activity/searchresult
    defaults: { _controller: MobileAppBundle:Activity:searchresult }

mobile_app_activity_testpage:
    path:     /mobapp/test
    defaults: { _controller: MobileAppBundle:Activity:test }

mobile_app_activity_listpage:
    path:     /mobapp/activity/list/{page}
    defaults: { _controller: MobileAppBundle:Activity:list }

mobile_app_activity_toplistpage:
    path:     /mobapp/activity/toplist/{page}
    defaults: { _controller: MobileAppBundle:Activity:toplist }

mobile_app_activity_page:
    path:     /mobapp/activity/show/{id}
    defaults: { _controller: MobileAppBundle:Activity:show }

mobile_app_activity_userpage:
    path:     /mobapp/activity/user/{iduser}/{numpage}
    defaults: { _controller: MobileAppBundle:Activity:user }

mobile_app_activity_deletepage:
    path:     /mobapp/activity/delete
    defaults: { _controller: MobileAppBundle:Activity:delete }

mobile_app_activity_uploadpage:
    path:     /mobapp/activity/image/upload
    defaults: { _controller: MobileAppBundle:Activity:upload }

mobile_app_user_loginpage:
    path:     /mobapp/user/login
    defaults: { _controller: MobileAppBundle:User:login }

mobile_app_user_registerpage:
    path:     /mobapp/user/register
    defaults: { _controller: MobileAppBundle:User:register }

mobile_app_user_updatepage:
    path:     /mobapp/user/update
    defaults: { _controller: MobileAppBundle:User:update }
