<?php

namespace BusinessModelBundle\Entity;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
				
				public function myFindAll()
				{
				return $this->createQueryBuilder('p')->getQuery()->getResult();
				}

				
				public function myFindOne($id)
				{
				// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
				$qb = $this->createQueryBuilder('p')
				->where('p.id = :id')
				->setParameter('id', $id);
				return ($qb->getQuery()->getResult()==null)? null : $qb->getQuery()->getResult()[0];
				}
				
	
				public function myFindOneByTitre($titrePage)
				{
				// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
				$qb = $this->createQueryBuilder('p')
				->where('p.titrePage = :titrePage')
				->setParameter('titrePage', $titrePage);
				return ($qb->getQuery()->getResult()==null)? null : $qb->getQuery()->getResult()[0];
				}

}
